# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Test
              run: dotnet test --no-build --verbosity normal

            - name: Install Required Tools
              run: |
                  dotnet new tool-manifest
                  dotnet tool install dotnet-reportgenerator-globaltool
                  dotnet tool install dotnet-coverage

            - name: Run the unit tests with code coverage
              run: |
                  dotnet coverage collect dotnet test --output ${{ github.workspace }}/Tests/Coverage.cobertura.xml --output-format cobertura

            - name: Generate Report
              run: |
                  dotnet reportgenerator -reports:${{ github.workspace }}/Tests/Coverage.cobertura.xml -targetdir:"${{ github.workspace }}/Tests/coveragereport" -reporttypes:Html -assemblyfilters:+MinimalApi
